# Generated by Django 2.2.6 on 2019-10-17 22:23

from django.db import migrations, models
import django.db.models.deletion
import itracker.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=63)),
                ('last_name', models.CharField(max_length=63)),
                ('address', models.CharField(max_length=63)),
                ('zip', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('barcode', models.CharField(default=itracker.models.generate_barcode, max_length=21)),
                ('status_code', models.CharField(choices=[('not_shipped', 'Not shipped'), ('sent_distribution', 'sent to distribution center'), ('sorted_distribution', 'sorted at distribution center'), ('shipped', 'Shipped'), ('delivered', 'Delivered')], max_length=32)),
                ('signature', models.BooleanField()),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itracker.Recipient')),
            ],
        ),
    ]
