# Generated by Django 3.1.1 on 2020-09-09 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('itracker', '0003_auto_20200909_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='status',
        ),
        migrations.AddField(
            model_name='shippingstatus',
            name='parcel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='itracker.parcel'),
            preserve_default=False,
        ),
    ]
