# Generated by Django 3.1.1 on 2020-09-09 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itracker', '0005_auto_20200909_1214'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parcel',
            name='status_code',
        ),
    ]
