# Generated by Django 3.1.1 on 2020-09-09 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itracker', '0006_remove_parcel_status_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipient',
            name='telephone',
            field=models.CharField(default='string', max_length=20),
            preserve_default=False,
        ),
    ]
